apiVersion: 1

datasources:
  - name: f1-telemetry
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 50ms
      httpMethod: GET