{
 "title": "F1 Telemetry Client Go",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "2023-02-13T09:07:49.957Z", "to": "2023-02-13T09:08:35.101Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_resident_memory_bytes, pod)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Brake Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_brake_temp{brake=~\"fl|fr|rl|rr\",job=\"f1-telemetry\"}",
     "legendFormat": "{{brake}}"
    }
   ]
  },
  {
   "title": "Tyres Wear",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_tyre_wear{tyre=~\"fl|fr|rl|rr\"}",
     "legendFormat": "{{tyre}}"
    }
   ]
  },
  {
   "title": "Accelation",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_acceleration{axis=~\"x|y|z\",job=\"f1-telemetry\"}",
     "legendFormat": "{{axis}}"
    }
   ]
  },
  {
   "title": "Tyre Age Lap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_tyres_age_lap{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Damage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_damage{damage=~\"Diffuser|Engine|EngineMGUKWear|Floor|FrontLeftWing|FrontRightWing|GearBox|RearWing\",job=\"f1-telemetry\"}",
     "legendFormat": "{{damage}}"
    }
   ]
  },
  {
   "title": "Fuel In Tank",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "f1_telemetry_fuel{fuel=\"FuelInTank\"}",
     "legendFormat": "{{fuel}}"
    }
   ]
  },
  {
   "title": "Current Lap Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_current_lap_num{job=\"f1-telemetry\"}"
    }
   ]
  },
  {
   "title": "Current Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_car_speed{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Brake",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "f1_telemetry_brake{job=\"f1-telemetry\"}",
     "legendFormat": "throttle"
    }
   ]
  },
  {
   "title": "Fastest Lap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_fastest_lap{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Fuel Remaining Laps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_fuel{fuel=\"FuelRemainingLaps\",job=\"f1-telemetry\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed Trap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_speed_trap{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Car Speed Monitor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    { "expr": "f1_telemetry_car_speed{}", "legendFormat": "car speed" }
   ]
  },
  {
   "title": "Last Lap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_last_lap{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Current Lap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_current_lap{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Engine RPM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f1_telemetry_car_engine_rpm{job=\"f1-telemetry\"}"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "f1_telemetry_throttle{job=\"f1-telemetry\"}",
     "legendFormat": "throttle"
    }
   ]
  },
  {
   "title": "ERS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 7, "y": 13 },
   "targets": [
    {
     "expr": "f1_telemetry_ers{ERS=~\"ERSDeployedThisLap|ERSHarvestedThisLapMGUH|ERSHarvestedThisLapMGUK|ERSStoreEnergy\",job=\"f1-telemetry\"}",
     "legendFormat": "{{ERS}}"
    }
   ]
  },
  {
   "title": "Accelation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "expr": "f1_telemetry_acceleration{axis=~\"x|y|z\",job=\"f1-telemetry\"}",
     "legendFormat": "{{axis}}"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "f1_telemetry_gear{job=\"f1-telemetry\"}",
     "legendFormat": "throttle"
    }
   ]
  },
  {
   "title": "Car Engime RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "f1_telemetry_car_engine_rpm{}", "legendFormat": "car engine rpm" }
   ]
  },
  {
   "title": "Atiitude",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "radian" } },
   "targets": [
    {
     "expr": "f1_telemetry_attitude{axis=~\"Pitch|Roll|Yaw\",job=\"f1-telemetry\"}",
     "legendFormat": "{{axis}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}: {{quantile}}"
    }
   ]
  }
 ]
}